# Generated by Django 4.1.2 on 2022-10-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('I', 'in'), ('O', 'out')], max_length=1)),
                ('amount', models.IntegerField()),
                ('method', models.CharField(choices=[('B', 'Bacs'), ('C', 'Card'), ('S', 'Cash'), ('Q', 'Cheque'), ('P', 'PayPal')], max_length=1)),
                ('category', models.CharField(choices=[('A', 'Allowance'), ('F', 'Food'), ('L', 'Leisure'), ('O', 'Offer'), ('T', 'Transport'), ('_', 'Other')], max_length=1)),
                ('date', models.DateField()),
                ('participant', models.CharField(max_length=64)),
            ],
        ),
    ]
