# Generated by Django 4.1.2 on 2022-10-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out')], max_length=1),
        ),
    ]
