# Generated by Django 4.1.2 on 2022-10-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_transaction_category_alter_transaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='participant',
            field=models.CharField(default='', max_length=64),
        ),
    ]
