# Generated by Django 4.1.2 on 2022-10-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_amortisationtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortisationtarget',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
