# Generated by Django 4.1.2 on 2022-10-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_transaction_amortisation_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amortisation_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.amortisationtarget'),
        ),
    ]
