# Generated by Django 4.1.2 on 2022-10-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_rename_amortisation_tag_transaction_amortisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortisationtarget',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
