# Generated by Django 4.1.2 on 2022-11-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_amortisationtarget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amortisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.amortisationtarget'),
        ),
    ]
